# Generated by Django 3.2.8 on 2021-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdutctsName', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('CurrentStock', models.IntegerField(verbose_name='Estoque Atual')),
                ('MinimumStock', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
            ],
            options={
                'verbose_name': 'Produtos',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
